from agents.idea_refiner.generation.models import LABELS, MODELS


def print_results(theme: str | None, state: dict, total_elapsed: float, today: str) -> None:
    winner_label = state["winner_label"]
    winner_model = MODELS[LABELS.index(winner_label)]["name"]
    print("\n" + "=" * 80)
    print(f"💡 DAILY BUSINESS IDEA — {today}")
    print(f"   Generated by: {winner_model}")
    print("   Judged by: Gemini 3.1 Pro Preview")
    print(f"   Today's theme: {theme or 'OPEN (no theme)'}")
    print(f"   Total time: {total_elapsed:.1f}s")
    if state["all_evals"]:
        print("\n   ⚖️  Scoreboard:")
        print(f"   {'Model':<25} {'Acq':>4} {'Dem':>4} {'Bld':>4} {'Total':>6}")
        print(f"   {'─'*25} {'─'*4} {'─'*4} {'─'*4} {'─'*6}")
        for ev in sorted(
            state["all_evals"],
            key=lambda e: (
                e["acquisition_score"] + e["demand_score"] + e.get("build_score", 0)
            ),
            reverse=True,
        ):
            label = ev["idea_label"]
            model_name = MODELS[LABELS.index(label)]["name"]
            total = (
                ev["acquisition_score"] + ev["demand_score"] + ev.get("build_score", 0)
            )
            marker = " 🏆" if label == winner_label else ""
            print(
                f"   {model_name:<25} {ev['acquisition_score']:>4} "
                f"{ev['demand_score']:>4} {ev.get('build_score', 0):>4} "
                f"{total:>5}/30{marker}"
            )
        if state["winner_ev"]:
            print(f"\n   Judge says: {state['winner_ev']['explanation']}")
    print("=" * 80 + "\n")
    print(state["winning_idea"])
    print("\n" + "=" * 80 + "\n")
